"""Compatibility facade for artifact validation."""

from __future__ import annotations

import hashlib
import json
import os
import shlex
import stat
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path, PureWindowsPath
from typing import Any
from .action_gate import ACTION_LEDGER_GATE_POLICY_SCHEMA_VERSION, ACTION_LEDGER_GATE_SCHEMA_VERSION, evaluate_action_ledger_gate
from .action_ledger import ACTION_LEDGER_SCHEMA_VERSION
from .adapters import TRACE_SCHEMA_VERSION
from .agentic_training_result import (
    AGENTIC_TRAINING_RESULT_SCHEMA_VERSION,
    BLOCK_REGISTRATION_RECOMMENDATION,
    FAILURE_CLASSES,
    OUTPUT_ARTIFACT_ROLES,
    RECOVERABLE_FAILURE_CLASSES,
    REGISTER_FAILURE_RECOMMENDATION,
    REGISTER_RESULT_RECOMMENDATION,
    RESULT_STATUSES,
)
from .agentic_training_flow import (
    AGENTIC_TRAINING_FLOW_SCHEMA_VERSION,
    BLOCKED_FLOW_MODE_CATEGORIES,
    BLOCKED_TRAINER_FLOW_MODES,
    BLOCKED_TRAINER_FLOW_STAGES,
    EXECUTABLE_FLOW_MODES,
    EXECUTABLE_STAGES,
    FLOW_BLOCK_RECOMMENDATION,
    FLOW_READY_RECOMMENDATION,
)
from .agentic_training_runtime import (
    AGENTIC_TRAINING_RUNTIME_PREFLIGHT_SCHEMA_VERSION,
    PLAN_READY_RECOMMENDATION,
    RUNTIME_BLOCK_RECOMMENDATION,
    RUNTIME_READY_RECOMMENDATION,
)
from .agentic_training_loop_plan import (
    AGENTIC_TRAINING_LOOP_PLAN_SCHEMA_VERSION,
    CLOUD_TRAINING_LINEAGE_ARTIFACT_ROLES,
    CLOUD_TRAINING_HANDOFF_LINEAGE_LINKS,
    PHASES as AGENTIC_TRAINING_LOOP_PHASES,
    PLAN_READINESS_CHECK_IDS,
    PLAN_REQUIRED_ARTIFACT_ROLES,
    build_agentic_training_loop_plan as _build_agentic_training_loop_plan,
    _cloud_training_launch_receipt_semantic_passed as _loop_cloud_training_launch_receipt_semantic_passed,
    _cloud_training_status_receipt_semantic_passed as _loop_cloud_training_status_receipt_semantic_passed,
    _cloud_training_completion_state as _loop_cloud_training_completion_state,
    _cloud_training_completion_status as _loop_cloud_training_completion_status,
    _agentic_training_result_plan_bound as _loop_agentic_training_result_plan_bound,
    _execution_completion as _loop_execution_completion,
    _execution_result_status as _loop_execution_result_status,
    _external_eval_receipt_semantic_passed as _loop_external_eval_receipt_semantic_passed,
    _phase_row as _build_agentic_training_loop_phase,
)
from .agentic_loop_ledger import (
    AGENTIC_LOOP_LEDGER_SCHEMA_VERSION,
    _decision as _build_agentic_loop_ledger_decision,
    _iteration_record as _build_agentic_loop_ledger_iteration,
    _metrics as _build_agentic_loop_ledger_metrics,
    _readiness_digest as _build_agentic_loop_ledger_readiness_digest,
)
from .agentic_loop_governance import (
    AGENTIC_LOOP_GOVERNANCE_RECEIPT_SCHEMA_VERSION,
    GOVERNANCE_ACTIONS,
    _execution_boundary as _build_agentic_loop_governance_boundary,
    _receipt_projection as _build_agentic_loop_governance_projection,
    _source_ledger_ref as _build_agentic_loop_governance_ledger_ref,
)
from .artifacts import CONTRACT_SCOPES, SUITE_TREND_SCHEMA_VERSION
from .bundle import (
    EVIDENCE_BUNDLE_NOTES,
    EVIDENCE_BUNDLE_SCHEMA_VERSION,
    HARNESS_RUN_MANIFEST_SCHEMA_VERSION,
    HARNESS_RUN_RESULT_SCHEMA_VERSION,
    _decision_key_metrics as _build_evidence_bundle_decision_key_metrics,
    _decision_text as _build_evidence_bundle_decision_text,
    _next_actions as _build_evidence_bundle_next_actions,
)
from .calibration import REVIEW_CALIBRATION_SCHEMA_VERSION, build_review_calibration
from .cloud_training import (
    CLOUD_TRAINING_ARTIFACT_MANIFEST_SCHEMA_VERSION,
    CLOUD_TRAINING_LAUNCH_PLAN_SCHEMA_VERSION,
    CLOUD_TRAINING_LAUNCH_RECEIPT_SCHEMA_VERSION,
    CLOUD_TRAINING_PREFLIGHT_SCHEMA_VERSION,
    CLOUD_TRAINING_PROVIDER_REGISTRY_SCHEMA_VERSION,
    CLOUD_TRAINING_STATUS_RECEIPT_SCHEMA_VERSION,
    PROVIDER_ADAPTER_RECEIPT_TYPES,
    PROVIDER_ADAPTER_RECEIPT_TYPES_BY_VERSION,
)
from .cloud_training_completion import (
    CLOUD_TRAINING_COMPLETION_RECEIPT_SCHEMA_VERSION,
    build_cloud_training_completion_receipt,
)
from .schema_registry import SchemaRegistryError, check_schema_contract, check_schema_file
from .trajectory_v2 import check_trajectory_v2
from .source_contract import (
    get_active_opaque_output_attestation,
    inspect_artifact_source,
)
from .compare_gate import compare_movement_summary
from .dataset_curation import (
    DATASET_CURATION_RECEIPT_SCHEMA_VERSION,
    training_export_lineage_status,
)
from .data_governance import task_contract_fingerprint
from .decision_gate import DECISION_GATE_SCHEMA_VERSION, decision_gate_source_contract_errors
from .digest import RUN_DIGEST_SCHEMA_VERSION
from .evidence import EVIDENCE_COVERAGE_SCHEMA_VERSION
from .eval_summary import (
    EVAL_SUMMARY_SCHEMA_VERSION,
    LabeledPath,
    _external_adapter_plan as _build_eval_summary_external_plan,
    _external_adapter_result as _build_eval_summary_external_result,
    _external_result_association_risks as _build_eval_summary_external_result_risks,
    _heldout_scenario_summary as _build_eval_summary_heldout,
    _suite_arm,
)
from .external_eval import (
    ADAPTERS,
    EXTERNAL_EVAL_ADAPTER_CONTRACT_VERSION,
    EXTERNAL_EVAL_ADAPTER_RECEIPT_TYPES,
    EXTERNAL_EVAL_PLAN_SCHEMA_VERSION,
    EXTERNAL_EVAL_RECEIPT_SCHEMA_VERSION,
    ExternalEvalPlanError,
    build_external_eval_receipt,
    external_eval_plan_semantic_errors,
)
from .external_eval_result import (
    EXTERNAL_EVAL_RESULT_SCHEMA_VERSION,
    ExternalEvalResultError,
    build_external_eval_result,
)
from .heldout_manifest import (
    HELDOUT_MANIFEST_SCHEMA_VERSION,
    _manifest_status as _build_heldout_manifest_status,
    _source_fields_from_suite_summary as _build_heldout_source_fields,
)
from .hermes_plugin import LIVE_SMOKE_SUMMARY_SCHEMA_VERSION
from .improvement_gate import (
    IMPROVEMENT_LEDGER_GATE_POLICY_SCHEMA_VERSION,
    IMPROVEMENT_LEDGER_GATE_SCHEMA_VERSION,
    evaluate_improvement_ledger_gate,
)
from .improvement_ledger import IMPROVEMENT_LEDGER_SCHEMA_VERSION, stable_work_key
from .improvement_plan import IMPROVEMENT_PLAN_SCHEMA_VERSION, PRIORITIES, work_item_fingerprint
from .lineage import LINEAGE_SCHEMA_VERSION, REPLAY_BUNDLE_SCHEMA_VERSION
from .agentic_training_plan import (
    ADVANCED_REWARD_MODES as PLAN_ADVANCED_REWARD_MODES,
    AGENTIC_TRAINING_PLAN_SCHEMA_VERSION,
    DEFAULT_EXECUTABLE_MODES as PLAN_DEFAULT_EXECUTABLE_MODES,
    FUTURE_RL_MODES as PLAN_FUTURE_RL_MODES,
    MODE_STAGE_SEQUENCES as PLAN_MODE_STAGE_SEQUENCES,
    MODE_VIEW_REQUIREMENTS as PLAN_MODE_VIEW_REQUIREMENTS,
    SUPPORTED_MODES as PLAN_SUPPORTED_MODES,
)
from .model_registry import (
    MODEL_ADAPTER_MANIFEST_SCHEMA_VERSION,
    MODEL_CANDIDATE_SCHEMA_VERSION,
    MODEL_COMPATIBILITY_REPORT_SCHEMA_VERSION,
    MODEL_REGISTRY_ENTRY_SCHEMA_VERSION,
    MODEL_REGISTRY_SCHEMA_VERSION,
    MODEL_SCOUT_MANIFEST_SCHEMA_VERSION,
    MODEL_SERVING_PROBE_RECEIPT_SCHEMA_VERSION,
    TRAINING_PLAN_SCHEMA_VERSION,
    is_training_license_approved,
    model_adapter_manifest_errors,
    model_candidate_errors,
    model_compatibility_report_errors,
    model_registry_entry_errors,
    model_registry_errors,
    model_scout_manifest_errors,
    model_serving_probe_receipt_errors,
    training_plan_errors,
)
from .model_grader import (
    MODEL_GRADER_DISAGREEMENT_QUEUE_SCHEMA_VERSION,
    MODEL_GRADER_DRY_RUN_SCHEMA_VERSION,
    MODEL_GRADER_GATE_SCHEMA_VERSION,
    MODEL_GRADER_OVERRIDE_RECEIPT_SCHEMA_VERSION,
    RUBRIC_SPEC_SCHEMA_VERSION,
    ModelGraderError,
    _model_grader_review_lineage_status,
    build_model_grader_gate,
)
from .next_iteration_schedule import NEXT_ITERATION_SCHEDULE_SCHEMA_VERSION
from .preflight import (
    TRAINER_DIRECTORY_TREE_HASH_ALGORITHM,
    TRAINER_LAUNCH_CHECK_SCHEMA_VERSION,
    TRAINER_PREFLIGHT_SEMANTIC_GATE_ROLES,
    TRAINER_PREFLIGHT_SCHEMA_VERSION,
    TRAINER_PREFLIGHT_SOURCE_ARTIFACT_FIELDS,
    TrainerPreflightError,
    build_trainer_launch_check,
    build_trainer_preflight_source_artifact,
    trainer_preflight_gate_semantics_ready,
)
from .governance import (
    PROMOTION_ALIAS_APPLY_SCHEMA_VERSION,
    PROMOTION_ALIAS_APPLY_CHECK_IDS,
    PROMOTION_CARDS_REQUIRED_INPUTS,
    PROMOTION_CARDS_SCHEMA_VERSION,
    PROMOTION_DECISION_REQUIRED_ARTIFACTS,
    PROMOTION_DECISION_REQUIRED_PASS_CHECK_IDS,
    PROMOTION_DECISION_SCHEMA_VERSION,
    PROMOTION_POLICY_DEFAULT_LIMITS,
    PROMOTION_POLICY_REQUIRED_FORBIDDEN_RULES,
    PROMOTION_POLICY_SCHEMA_VERSION,
    PROMOTION_ROLLBACK_RECEIPT_SCHEMA_VERSION,
    PROMOTION_RELEASE_RECORD_REQUIRED_ARTIFACTS,
    PROMOTION_RELEASE_RECORD_VALIDATED_ARTIFACTS,
    PROMOTION_RELEASE_RECORD_SCHEMA_VERSION,
    _JSON_ARTIFACT_ROLES as _PROMOTION_JSON_ARTIFACT_ROLES,
    build_promotion_decision as _build_promotion_decision,
    _decision_metrics as _build_promotion_decision_metrics,
    _promotion_external_eval_checks as _build_promotion_external_eval_checks,
    _promotion_external_eval_lineage as _build_promotion_external_eval_lineage,
    promotion_release_record_check_ids,
)
from .promotion_archive import PROMOTION_ARCHIVE_SCHEMA_VERSION
from .promotion_gate import (
    PROMOTION_LEDGER_GATE_POLICY_SCHEMA_VERSION,
    PROMOTION_LEDGER_GATE_SCHEMA_VERSION,
    evaluate_promotion_ledger_gate,
)
from .promotion_ledger import PROMOTION_LEDGER_SCHEMA_VERSION
from .repair import REPAIR_ITEM_SCHEMA_VERSION, REPAIR_QUEUE_SCHEMA_VERSION
from .rejection_sampling import REJECTION_SAMPLING_GATE_SCHEMA_VERSION, _review_lineage_status
from .review import (
    REVIEW_CONFIDENCE_LEVELS,
    REVIEW_ITEM_SCHEMA_VERSION,
    REVIEW_LABEL_SCHEMA_VERSION,
    REVIEW_LABELS,
    REVIEW_MANIFEST_SCHEMA_VERSION,
    TRAINING_NEGATIVE_LABELS,
    review_item_sha256,
    _reviewed_dpo as _build_reviewed_dpo,
    _reviewed_labels as _build_reviewed_labels,
    _reviewed_preferences as _build_reviewed_preferences,
    _reviewed_reward_model as _build_reviewed_reward_model,
    _reviewed_action_sft as _build_reviewed_action_sft,
    _reviewed_sft as _build_reviewed_sft,
    REVIEWED_DPO_SCHEMA_VERSION,
    REVIEWED_LABEL_SCHEMA_VERSION,
    REVIEWED_MANIFEST_SCHEMA_VERSION,
    REVIEWED_PREFERENCE_SCHEMA_VERSION,
    REVIEWED_REWARD_MODEL_SCHEMA_VERSION,
    REVIEWED_SFT_SCHEMA_VERSION,
    _reviewed_dataset_version_id,
)
from .reviewed_gate import (
    REVIEWED_EXPORT_SOURCE_ARTIFACT_FIELDS,
    REVIEWED_GATE_SCHEMA_VERSION,
    ReviewedGateError,
    build_reviewed_export_source_artifact,
    evaluate_reviewed_gate,
)
from .review_semantics import (
    REVIEWED_ACTION_SFT_SCHEMA_VERSION,
)
from .rollout_generation import AGENTIC_ROLLOUT_PLAN_SCHEMA_VERSION, AGENTIC_ROLLOUT_RECEIPT_SCHEMA_VERSION
from .runtime_adapter_router import (
    ADAPTER_ROUTE_DECISION_SCHEMA_VERSION,
    TOOL_CAPABILITY_SELECTION_SCHEMA_VERSION,
    canonical_sha256 as _router_canonical_sha256,
    validate_adapter_route_decision as _validate_adapter_route_decision_semantics,
    validate_tool_capability_selection as _validate_tool_capability_selection_semantics,
)
from .path_safety import (
    path_has_symlink_component as _path_has_symlink_component,
    resolve_artifact_reference_path,
)
from .scorers import SCORE_SCHEMA_VERSION, TASK_COMPLETION_SCHEMA_VERSION
from .scenario_check import SCENARIO_CHECK_SCHEMA_VERSION
from .scenario_quality import SCENARIO_QUALITY_SCHEMA_VERSION
from .state_capture import STATE_SNAPSHOT_SCHEMA_VERSION
from .state_diff import STATE_DIFF_SCHEMA_VERSION, resolve_state_diff_semantics
from .trace_observability import TRACE_OBSERVABILITY_SCHEMA_VERSION, build_trace_signal
from .trainer_archive import TRAINER_ARCHIVE_SCHEMA_VERSION
from .trainer_archive_check import TRAINER_ARCHIVE_CHECK_SCHEMA_VERSION
from .trainer_consumer_plan import TRAINER_CONSUMER_PLAN_SCHEMA_VERSION
from .training import (
    DATASET_SPLIT_ARTIFACTS,
    DATASET_SPLIT_NAMES,
    RL_CURRICULUM_SCHEMA_VERSION,
    RL_ACTION_SFT_SCHEMA_VERSION,
    RL_DATASET_REGISTRY_SCHEMA_VERSION,
    RL_DATASET_METRICS_SCHEMA_VERSION,
    RL_DATASET_SPLITS_SCHEMA_VERSION,
    RL_DPO_SCHEMA_VERSION,
    RL_EPISODE_SCHEMA_VERSION,
    RL_FAILURE_MODE_SCHEMA_VERSION,
    RL_LABEL_PROVENANCE_SCHEMA_VERSION,
    COMPARE_RL_DPO_SCHEMA_VERSION,
    COMPARE_RL_MANIFEST_SCHEMA_VERSION,
    COMPARE_RL_PAIR_SCHEMA_VERSION,
    RL_MANIFEST_SCHEMA_VERSION,
    RL_PREFERENCE_SCHEMA_VERSION,
    RL_REWARD_SCHEMA_VERSION,
    RL_REWARD_MODEL_SCHEMA_VERSION,
    RL_SFT_SCHEMA_VERSION,
    RL_STEP_REWARD_SCHEMA_VERSION,
    RL_TRAINER_VIEWS_CONTRACT_VERSION,
    REWARD_SCALES,
    build_label_provenance_summary,
    build_redaction_status,
    positive_label_eligible,
    redaction_scan_artifacts,
)
from .verifiers import VERIFIER_SOURCES_SCHEMA_VERSION
from .hashing import sha256_file as _sha256
from ._validation.cloud import _CLOUD_TRAINING_ADAPTER_CONTRACT_KEYS, _CLOUD_TRAINING_ARTIFACT_MANIFEST_KEYS, _CLOUD_TRAINING_CONSTRAINT_KEYS, _CLOUD_TRAINING_CREDENTIAL_CHECK_KEYS, _CLOUD_TRAINING_EXECUTION_BOUNDARY_KEYS, _CLOUD_TRAINING_HANDOFF_CONTRACT_KEYS, _CLOUD_TRAINING_LAUNCH_KEYS, _CLOUD_TRAINING_LAUNCH_PLAN_KEYS, _CLOUD_TRAINING_LAUNCH_PLAN_LAUNCH_KEYS, _CLOUD_TRAINING_LAUNCH_PLAN_PROVIDER_CHAIN_KEYS, _CLOUD_TRAINING_LIVE_DEPENDENCY_CHECK_KEYS, _CLOUD_TRAINING_LIVE_PREFLIGHT_KEYS, _CLOUD_TRAINING_PREFLIGHT_KEYS, _CLOUD_TRAINING_PROVIDER_KEYS, _CLOUD_TRAINING_PROVIDER_REGISTRY_KEYS, _CLOUD_TRAINING_RECEIPT_CHECK_KEYS, _CLOUD_TRAINING_SOURCE_ARTIFACT_KEYS, _CLOUD_TRAINING_STATUS_KEYS, _CLOUD_TRAINING_TRANSFER_ARTIFACT_KEYS, _CLOUD_TRAINING_TRANSFER_PLAN_KEYS, _cloud_training_check_by_id, _cloud_training_provider_id_from_source_ref, _cloud_training_required_source_artifacts, _cloud_training_schema_check_passed, _cloud_training_source_state, _expected_cloud_training_launch_plan_provider_chain, _is_replayable_cloud_training_ref_path, _is_safe_or_redacted_cloud_training_ref_path, _resolve_cloud_training_artifact_path, _resolve_regular_cloud_training_artifact_path, _validate_cloud_training_adapter_contract, _validate_cloud_training_artifact_ref, _validate_cloud_training_artifact_refs, _validate_cloud_training_command_token_public_path, _validate_cloud_training_completion_source_ref, _validate_cloud_training_constraints, _validate_cloud_training_contract, _validate_cloud_training_credentials, _validate_cloud_training_expected_state, _validate_cloud_training_handoff_contract, _validate_cloud_training_launch_plan_launch, _validate_cloud_training_launch_plan_provider_chain, _validate_cloud_training_launch_plan_provider_matches_chain, _validate_cloud_training_launch_plan_readiness, _validate_cloud_training_launch_plan_source_refs, _validate_cloud_training_launch_receipt_readiness, _validate_cloud_training_live_preflight, _validate_cloud_training_preflight_source_readiness, _validate_cloud_training_provider_record, _validate_cloud_training_receipt_allowed_keys, _validate_cloud_training_receipt_checks, _validate_cloud_training_source_artifacts, _validate_cloud_training_source_state, _validate_cloud_training_status_receipt_readiness, _validate_cloud_training_transfer_plan, validate_cloud_training_artifact_manifest, validate_cloud_training_completion_receipt, validate_cloud_training_launch_plan, validate_cloud_training_launch_receipt, validate_cloud_training_preflight, validate_cloud_training_provider_registry, validate_cloud_training_status_receipt
from ._validation.constants import EVAL_SUITE_MANIFEST_SCHEMA_VERSION, HARNESS_REPLAY_RESULT_SCHEMA_VERSION, HARNESS_SUITE_RESULT_SCHEMA_VERSION, LEGACY_LIVE_SMOKE_SUMMARY_SCHEMA_VERSIONS, RUN_SUITE_HARNESS_SOURCE, RUN_SUITE_SCHEMA_VERSION, SERVING_CAPABILITY_STATUSES, SERVING_COMPATIBILITY_REPORT_SCHEMA_VERSION, SERVING_DEMO_RUN_SCHEMA_VERSION, SERVING_ENDPOINT_CHECK_SCHEMA_VERSION, SERVING_LIFECYCLE_PREFLIGHT_ARTIFACTS, SERVING_LIFECYCLE_SCHEMA_VERSION, SERVING_PROFILE_SCHEMA_VERSION, TRAINER_WRAPPER_DRY_RUN_SCHEMA_VERSION, VALIDATION_SCHEMA_VERSION, _COMPANION_NOT_PROVIDED
from ._validation.dispatch import validate_artifacts
from ._validation.evaluation_serving import _AGENTIC_ROLLOUT_BATCH_KEYS, _AGENTIC_ROLLOUT_CHECK_KEYS, _AGENTIC_ROLLOUT_ENVIRONMENT_KEYS, _AGENTIC_ROLLOUT_MOCK_ROW_KEYS, _AGENTIC_ROLLOUT_PLAN_BOUNDARY_KEYS, _AGENTIC_ROLLOUT_PLAN_BUDGET_KEYS, _AGENTIC_ROLLOUT_PLAN_KEYS, _AGENTIC_ROLLOUT_PLAN_LINEAGE_KEYS, _AGENTIC_ROLLOUT_POLICY_KEYS, _AGENTIC_ROLLOUT_RECEIPT_BOUNDARY_KEYS, _AGENTIC_ROLLOUT_RECEIPT_KEYS, _AGENTIC_ROLLOUT_RECEIPT_LINEAGE_KEYS, _AGENTIC_ROLLOUT_RECEIPT_SOURCE_PLAN_KEYS, _AGENTIC_ROLLOUT_REJECTION_SAMPLING_KEYS, _AGENTIC_ROLLOUT_SCENARIO_KEYS, _AGENTIC_ROLLOUT_VERIFIER_GATE_KEYS, _AGENTIC_ROLLOUT_VERIFIER_REF_KEYS, _DATASET_CURATION_BOUNDARY_KEYS, _DATASET_CURATION_DIRECTORY_REF_KEYS, _DATASET_CURATION_INPUT_KEYS, _DATASET_CURATION_RECEIPT_KEYS, _DATASET_CURATION_REF_KEYS, _DATASET_CURATION_SUMMARY_KEYS, _DATASET_CURATION_TRAINER_HANDOFF_KEYS, _EVAL_SUMMARY_ARM_KEYS, _EVAL_SUMMARY_COMPARISON_KEYS, _EVAL_SUMMARY_CONCLUSION_KEYS, _EVAL_SUMMARY_COST_KEYS, _EVAL_SUMMARY_EXTERNAL_ADAPTER_KEYS, _EVAL_SUMMARY_EXTERNAL_RESULT_KEYS, _EVAL_SUMMARY_GATE_FAILED_CHECK_KEYS, _EVAL_SUMMARY_GATE_KEYS, _EVAL_SUMMARY_GOVERNANCE_CLAIMS_KEYS, _EVAL_SUMMARY_HELDOUT_ARM_KEYS, _EVAL_SUMMARY_HELDOUT_KEYS, _EVAL_SUMMARY_HELDOUT_MISMATCH_KEYS, _EVAL_SUMMARY_KEYS, _EVAL_SUMMARY_LATENCY_KEYS, _EVAL_SUMMARY_METRIC_BASE_KEYS, _EVAL_SUMMARY_OPERATIONAL_KEYS, _EVAL_SUMMARY_RAW_MOVEMENT_KEYS, _EVAL_SUMMARY_REPAIR_KEYS, _EVAL_SUMMARY_RISK_KEYS, _EVAL_SUMMARY_SERVING_PREFLIGHT_KEYS, _EVAL_SUMMARY_SERVING_PREFLIGHT_SUMMARY_KEYS, _EVAL_SUMMARY_TASK_COMPLETION_KEYS, _EVAL_SUMMARY_TOKENS_KEYS, _EVAL_SUMMARY_WORK_ITEM_KEYS, _HELDOUT_MANIFEST_FINGERPRINT_MISMATCH_KEYS, _HELDOUT_MANIFEST_GOVERNANCE_KEYS, _HELDOUT_MANIFEST_KEYS, _HELDOUT_MANIFEST_MISMATCH_KEYS, _HELDOUT_MANIFEST_SOURCE_KEYS, _MODEL_GRADER_BOUNDARY_KEYS, _MODEL_GRADER_CHECK_KEYS, _MODEL_GRADER_DISAGREEMENT_KEYS, _MODEL_GRADER_DISAGREEMENT_QUEUE_KEYS, _MODEL_GRADER_DISAGREEMENT_QUEUE_OVERRIDE_REQUIREMENT_KEYS, _MODEL_GRADER_DISAGREEMENT_QUEUE_SOURCE_KEYS, _MODEL_GRADER_DRY_RUN_HUMAN_REVIEW_OVERRIDES_KEYS, _MODEL_GRADER_DRY_RUN_KEYS, _MODEL_GRADER_DRY_RUN_SOURCE_KEYS, _MODEL_GRADER_DRY_RUN_TRAINING_ADMISSION_KEYS, _MODEL_GRADER_FILE_REF_KEYS, _MODEL_GRADER_GATE_ADMISSION_KEYS, _MODEL_GRADER_GATE_KEYS, _MODEL_GRADER_GATE_METRICS_KEYS, _MODEL_GRADER_GATE_SOURCE_KEYS, _MODEL_GRADER_GRADER_KEYS, _MODEL_GRADER_LABEL_COUNT_KEYS, _MODEL_GRADER_LABEL_KEYS, _MODEL_GRADER_OVERRIDE_METRICS_KEYS, _MODEL_GRADER_OVERRIDE_QUEUE_KEYS, _MODEL_GRADER_OVERRIDE_RECEIPT_KEYS, _MODEL_GRADER_OVERRIDE_ROW_KEYS, _MODEL_GRADER_OVERRIDE_SOURCE_KEYS, _MODEL_GRADER_OVERRIDE_TRAINING_ADMISSION_KEYS, _MODEL_GRADER_REVIEW_EXPORT_KEYS, _MODEL_GRADER_RUBRIC_CALIBRATION_REQUIREMENT_KEYS, _MODEL_GRADER_RUBRIC_CRITERION_KEYS, _MODEL_GRADER_RUBRIC_FINGERPRINT_KEYS, _MODEL_GRADER_RUBRIC_SPEC_KEYS, _REJECTION_DATASET_CHECK_KEYS, _REJECTION_SAMPLING_GATE_BOUNDARY_KEYS, _REJECTION_SAMPLING_GATE_INPUT_KEYS, _REJECTION_SAMPLING_GATE_KEYS, _REJECTION_SAMPLING_GATE_POLICY_KEYS, _REJECTION_SAMPLING_GATE_REF_KEYS, _REJECTION_SAMPLING_GATE_ROLLOUT_REF_KEYS, _REJECTION_SAMPLING_GATE_SUMMARY_KEYS, _SERVING_CAPABILITY_CHECK_KEYS, _SERVING_COMPATIBILITY_CHECKS_KEYS, _SERVING_COMPATIBILITY_REPORT_KEYS, _SERVING_DEMO_RUN_KEYS, _SERVING_ENDPOINT_CHECK_KEYS, _SERVING_ENDPOINT_CHECK_ROW_KEYS, _SERVING_LIFECYCLE_ENDPOINT_KEYS, _SERVING_LIFECYCLE_ENVIRONMENT_KEYS, _SERVING_LIFECYCLE_KEYS, _SERVING_LIFECYCLE_LOG_KEYS, _SERVING_LIFECYCLE_READINESS_PROBE_KEYS, _SERVING_LIFECYCLE_SMOKE_CHECK_KEYS, _SERVING_LIFECYCLE_TEARDOWN_KEYS, _SERVING_PROFILE_CAPABILITY_KEYS, _SERVING_PROFILE_ENDPOINT_KEYS, _SERVING_PROFILE_IDENTITY_KEYS, _SERVING_PROFILE_KEYS, _SERVING_READINESS_KEYS, _agentic_rollout_reference_path, _count_eval_summary_work_item_field, _external_eval_input_blockers, _external_eval_input_present, _external_eval_reference_path, _heldout_manifest_reference_path, _heldout_manifest_source_from_suite_summary, _heldout_manifest_sources_replayable, _heldout_manifest_sources_with_identities, _is_public_dataset_curation_ref_path, _is_public_model_grader_ref_path, _is_public_rejection_sampling_ref_path, _is_replayable_agentic_rollout_ref_path, _is_replayable_external_eval_ref_path, _is_safe_or_redacted_agentic_rollout_ref_path, _is_safe_or_redacted_external_eval_ref_path, _model_grader_disagreement_queue_key, _model_grader_expected_label_source_key, _model_grader_gate_replay_policy, _model_grader_gate_source_attestations, _model_grader_label_counts, _model_grader_label_sha256, _model_grader_label_source_key, _model_grader_override_sha256, _model_grader_row_sha256, _rate_zero, _replay_model_grader_gate, _resolve_dataset_curation_ref_path, _resolve_eval_summary_source_path, _resolve_model_grader_source_path, _resolve_rejection_sampling_gate_ref_path, _resolve_serving_lifecycle_artifact_path, _resolve_suite_summary_ref_path, _same_model_grader_source_file, _serving_demo_expected_arm_metrics, _validate_agentic_mock_rollout, _validate_agentic_rollout_batch, _validate_agentic_rollout_environment, _validate_agentic_rollout_plan, _validate_agentic_rollout_policies, _validate_agentic_rollout_receipt, _validate_agentic_rollout_receipt_source_plan, _validate_agentic_rollout_rejection_sampling, _validate_agentic_rollout_scenarios, _validate_dataset_curation_directory_ref, _validate_dataset_curation_file_ref, _validate_dataset_curation_lineage, _validate_dataset_curation_receipt, _validate_dataset_curation_ref, _validate_eval_suite_manifest, _validate_eval_summary, _validate_eval_summary_arm, _validate_eval_summary_arm_serving_preflight, _validate_eval_summary_comparison, _validate_eval_summary_external_adapter, _validate_eval_summary_external_result, _validate_eval_summary_gate, _validate_eval_summary_heldout, _validate_eval_summary_heldout_replay, _validate_eval_summary_operational_metrics, _validate_eval_summary_repair_curriculum, _validate_eval_summary_serving_preflight_consistency, _validate_eval_summary_serving_preflight_summary, _validate_eval_summary_source_file_ref, _validate_eval_summary_suite_source_schema, _validate_eval_summary_work_item, _validate_evidence_coverage, _validate_evidence_coverage_metrics, _validate_evidence_coverage_runs, _validate_external_eval_adapter_contract, _validate_external_eval_adapter_plan, _validate_external_eval_adapter_receipt, _validate_external_eval_inputs, _validate_external_eval_plan, _validate_external_eval_receipt, _validate_external_eval_receipt_boundary, _validate_external_eval_receipt_launch, _validate_external_eval_receipt_replay, _validate_external_eval_receipt_source_plan, _validate_external_eval_result, _validate_external_eval_result_source_ref, _validate_external_eval_scenario_manifest_file, _validate_heldout_manifest, _validate_heldout_manifest_mismatch, _validate_heldout_manifest_source, _validate_heldout_manifest_source_file, _validate_model_grader_boundary, _validate_model_grader_check_keys, _validate_model_grader_checked_artifact, _validate_model_grader_disagreement_queue, _validate_model_grader_disagreement_queue_artifact, _validate_model_grader_disagreement_queue_sources, _validate_model_grader_dry_run, _validate_model_grader_dry_run_labels_match_review_items, _validate_model_grader_dry_run_review_export_matches_rubric, _validate_model_grader_dry_run_sources, _validate_model_grader_gate, _validate_model_grader_gate_sources, _validate_model_grader_override_receipt, _validate_model_grader_override_sources, _validate_model_grader_referenced_artifact, _validate_model_grader_review_export_ref, _validate_model_grader_source_file_ref, _validate_rejection_sampling_gate, _validate_rejection_sampling_gate_file_ref, _validate_rejection_sampling_gate_ref, _validate_rejection_sampling_review_lineage, _validate_rubric_review_item_fingerprints, _validate_rubric_spec, _validate_scenario_check, _validate_scenario_check_duplicates, _validate_scenario_check_rows, _validate_scenario_quality, _validate_scenario_quality_metrics, _validate_scenario_quality_rows, _validate_serving_capability_check, _validate_serving_compatibility_report, _validate_serving_demo_arm_metrics_against_scenarios, _validate_serving_demo_claim, _validate_serving_demo_comparison, _validate_serving_demo_comparison_outcome, _validate_serving_demo_endpoint_suite, _validate_serving_demo_metrics, _validate_serving_demo_run, _validate_serving_demo_scenario, _validate_serving_endpoint_check, _validate_serving_lifecycle, _validate_serving_lifecycle_preflight_artifacts, _validate_serving_lifecycle_readiness_probe, _validate_serving_lifecycle_smoke_check, _validate_serving_lifecycle_teardown, _validate_serving_profile, _validate_serving_readiness, _validate_suite_family_metrics, _validate_suite_metrics, _validate_suite_run_artifact_ref, _validate_suite_run_dir, _validate_suite_run_input_lineage_consistency, _validate_suite_run_input_ref, _validate_suite_run_scorecard_consistency, _validate_suite_summary, _validate_suite_trend, _validate_suite_trend_count_rows, _validate_suite_trend_point, validate_agentic_rollout_plan, validate_agentic_rollout_receipt, validate_dataset_curation_receipt, validate_eval_suite_manifest, validate_eval_summary, validate_evidence_coverage, validate_external_eval_plan, validate_external_eval_receipt, validate_external_eval_result, validate_harness_suite_result, validate_heldout_manifest, validate_model_grader_disagreement_queue, validate_model_grader_dry_run, validate_model_grader_gate, validate_model_grader_override_receipt, validate_rejection_sampling_gate, validate_rubric_spec, validate_scenario_check, validate_scenario_quality, validate_serving_compatibility_report, validate_serving_demo_run, validate_serving_endpoint_check, validate_serving_lifecycle, validate_serving_profile, validate_suite_summary, validate_suite_summary_payload_consistency, validate_suite_trend
from ._validation.exports import _compare_dpo_to_preference, _compare_event_detail, _compare_export_artifact_paths, _compare_improvement_dpo_to_pair, _compare_response_text, _cross_split_families, _dpo_source_fingerprints_verified, _expected_curriculum_priority_band, _expected_dataset_family_metrics, _expected_episode_trace_signal, _expected_row_split, _expected_source_fingerprint_coverage, _expected_task_completion_metrics, _expected_trace_signal_metrics, _expected_trainer_view_source_fingerprint_coverage, _fingerprints_have_source_evidence, _merge_count_rows_quiet, _paired_source_fingerprints_verified, _read_training_split_rows, _review_export_artifact_paths, _reviewed_export_artifact_paths, _row_source_fingerprints_verified, _rule_reward_deltas_by_key, _source_fingerprint_record_complete, _split_scenario_ids, _split_task_families, _training_export_artifact_paths, _validate_action_sft_records, _validate_agentic_messages, _validate_compare_dpo, _validate_compare_manifest, _validate_compare_pair_links, _validate_compare_pairs, _validate_compare_view, _validate_contract_fingerprint_inputs, _validate_contract_fingerprint_status, _validate_curriculum, _validate_dataset_card, _validate_dataset_family_metrics, _validate_dataset_metrics, _validate_dataset_registry, _validate_dataset_split_counts, _validate_dataset_split_leakage, _validate_dataset_split_summary, _validate_dataset_splits, _validate_dpo_records, _validate_dpo_trajectory_messages, _validate_episodes, _validate_failure_modes, _validate_improvement_card, _validate_manifest_artifact_fingerprints, _validate_matching_source_fingerprints, _validate_messages, _validate_pair_row_split_locality, _validate_preferences, _validate_quality_flags, _validate_reward_model_records, _validate_rewards, _validate_sft_records, _validate_source_fingerprint_coverage, _validate_source_fingerprint_fields, _validate_source_fingerprint_record, _validate_split_row_placement, _validate_step_rewards, _validate_trace_signal, _validate_trace_signal_metrics, _validate_trainer_view_source_fingerprint_coverage, _validate_training_manifest, _validate_training_view_common, _validate_training_view_task_completion, validate_compare_export, validate_training_export
from ._validation.governance import _COMPACT_VALIDATION_SUMMARY_KEYS, _COMPACT_VALIDATION_TARGET_KEYS, _PROMOTION_ALIAS_APPLY_ARTIFACT_KEYS, _PROMOTION_ALIAS_APPLY_DECISION_REF_KEYS, _PROMOTION_ALIAS_APPLY_KEYS, _PROMOTION_ALIAS_APPLY_METRICS_KEYS, _PROMOTION_ALIAS_HISTORY_ENTRY_KEYS, _PROMOTION_ARCHIVE_ARTIFACT_KEYS, _PROMOTION_ARCHIVE_KEYS, _PROMOTION_ARCHIVE_METRICS_KEYS, _PROMOTION_ARCHIVE_MISSING_KEYS, _PROMOTION_DECISION_ALIAS_ROW_KEYS, _PROMOTION_DECISION_ALIAS_UPDATE_KEYS, _PROMOTION_DECISION_BLOCKING_CHECK_KEYS, _PROMOTION_DECISION_BLOCK_KEYS, _PROMOTION_DECISION_KEYS, _PROMOTION_DECISION_METRICS_KEYS, _PROMOTION_DECISION_MODELS_KEYS, _PROMOTION_DECISION_MODEL_KEYS, _PROMOTION_EXTERNAL_EVAL_LINEAGE_KEYS, _PROMOTION_EXTERNAL_EVAL_RESULT_KEYS, _PROMOTION_FINGERPRINTED_ARTIFACT_KEYS, _PROMOTION_GATE_CHECK_KEYS, _PROMOTION_POLICY_KEYS, _PROMOTION_POLICY_REQUIREMENT_KEYS, _PROMOTION_RELEASE_RECORD_BINDINGS_KEYS, _PROMOTION_RELEASE_RECORD_KEYS, _PROMOTION_RELEASE_RECORD_METRICS_KEYS, _PROMOTION_RELEASE_RECORD_POLICY_KEYS, _PROMOTION_RELEASE_RECORD_RELEASE_KEYS, _PROMOTION_ROLLBACK_ARTIFACT_KEYS, _PROMOTION_ROLLBACK_BLOCK_KEYS, _PROMOTION_ROLLBACK_METRICS_KEYS, _PROMOTION_ROLLBACK_RECEIPT_KEYS, _action_ledger_actual_action_records, _action_ledger_evidence_record, _action_ledger_expected_action_record, _action_ledger_gate_check_policy_key, _action_ledger_gate_replay_options, _actual_improvement_eval_summary_item_records, _add_total, _append_scope_value, _bundle_validation_counts_consistent, _bundle_validation_has_targets, _count_value, _eval_summary_bundle_metrics, _eval_summary_item_record, _eval_summary_risk_source_counts, _evidence_bundle_action_fingerprint, _evidence_bundle_blocking_check_rows, _evidence_bundle_blocking_gate_rows, _expected_eval_summary_item_records, _expected_improvement_ledger_status, _improvement_ledger_gate_replay_options, _increment_count, _is_safe_relative_path, _list_present, _merge_action_ledger_gate_check_option, _merge_improvement_ledger_gate_check_option, _merge_promotion_ledger_gate_check_option, _promotion_archive_count_map, _promotion_artifact_path_uses_symlink_ancestor, _promotion_artifact_sha, _promotion_consecutive, _promotion_count_map, _promotion_existing_artifact_path, _promotion_ledger_expected_metrics, _promotion_ledger_gate_check_policy_key, _promotion_ledger_gate_replay_options, _promotion_model_id, _promotion_policy_without_artifact_path, _promotion_read_json_payload, _promotion_record_allowed, _promotion_record_blocked, _promotion_replay_artifact_path, _promotion_replay_uses_preserved_paths, _promotion_source_artifact_key, _resolve_action_ledger_bundle_path, _resolve_evidence_bundle_artifact_path, _resolve_gate_source_path, _resolve_promotion_decision_artifact_path, _serving_lifecycle_bundle_metrics, _validate_action_ledger, _validate_action_ledger_bundle, _validate_action_ledger_bundle_action_counts, _validate_action_ledger_bundle_linkage, _validate_action_ledger_count_rows, _validate_action_ledger_entry, _validate_action_ledger_gate, _validate_action_ledger_gate_decision, _validate_action_ledger_gate_metrics, _validate_action_ledger_gate_policy_check_coverage, _validate_action_ledger_gate_policy_summary, _validate_action_ledger_gate_source_linkage, _validate_action_ledger_occurrence, _validate_alias_history_entry, _validate_alias_receipt_candidate_entry_binding, _validate_alias_snapshot, _validate_bundle_eval_summary_metrics, _validate_bundle_gate_validation, _validate_bundle_harness_handoff, _validate_bundle_live_smoke_summary_paths, _validate_bundle_run_digest_coverage, _validate_bundle_serving_lifecycle_metrics, _validate_bundle_top_curriculum_priorities, _validate_bundle_trainer_handoff, _validate_bundle_validation_metrics, _validate_current_promotion_release_artifacts, _validate_current_registry_matches_alias_receipt, _validate_decision_gate, _validate_decision_gate_source_artifact, _validate_decision_gate_source_artifact_hash, _validate_decision_gate_source_decision_matches_artifact, _validate_evidence_bundle, _validate_evidence_bundle_artifact_directory_fingerprint, _validate_evidence_bundle_artifact_file_fingerprint, _validate_evidence_bundle_artifact_record, _validate_evidence_bundle_checks, _validate_evidence_bundle_decision, _validate_evidence_bundle_eval_summary, _validate_evidence_bundle_harness_checks, _validate_evidence_bundle_metrics, _validate_evidence_bundle_serving_lifecycle, _validate_evidence_bundle_validation_checks, _validate_fingerprinted_artifact, _validate_improvement_decision, _validate_improvement_item_sources, _validate_improvement_ledger, _validate_improvement_ledger_decision, _validate_improvement_ledger_entry, _validate_improvement_ledger_gate, _validate_improvement_ledger_gate_decision, _validate_improvement_ledger_gate_metrics, _validate_improvement_ledger_gate_policy_summary, _validate_improvement_ledger_gate_source_linkage, _validate_improvement_ledger_metrics, _validate_improvement_ledger_occurrence, _validate_improvement_ledger_plan, _validate_improvement_metrics, _validate_improvement_plan, _validate_improvement_plan_eval_summary_linkage, _validate_improvement_source_artifact, _validate_improvement_source_artifact_file_fingerprint, _validate_improvement_work_item, _validate_policy_class_list, _validate_policy_conservative_limits, _validate_policy_exact_roles, _validate_policy_forbidden_rules, _validate_policy_limits, _validate_policy_required_forbidden_rules, _validate_policy_requirements, _validate_policy_role_list, _validate_promotion_alias_apply, _validate_promotion_alias_apply_decision_validation, _validate_promotion_alias_apply_metrics, _validate_promotion_archive, _validate_promotion_archive_artifact, _validate_promotion_archive_metrics, _validate_promotion_archive_missing, _validate_promotion_card_text, _validate_promotion_cards, _validate_promotion_cards_metrics, _validate_promotion_decision, _validate_promotion_decision_alias_update, _validate_promotion_decision_artifact, _validate_promotion_decision_artifact_hash, _validate_promotion_decision_block, _validate_promotion_decision_check_replay, _validate_promotion_decision_metrics, _validate_promotion_decision_model, _validate_promotion_decision_required_pass_checks, _validate_promotion_external_eval_check_replay, _validate_promotion_external_eval_lineage, _validate_promotion_external_eval_result_artifact, _validate_promotion_external_eval_result_projection, _validate_promotion_fingerprinted_artifact, _validate_promotion_gate_check_keys, _validate_promotion_ledger, _validate_promotion_ledger_gate, _validate_promotion_ledger_gate_decision, _validate_promotion_ledger_gate_metrics, _validate_promotion_ledger_gate_policy_check_coverage, _validate_promotion_ledger_gate_policy_summary, _validate_promotion_ledger_gate_source_linkage, _validate_promotion_ledger_record, _validate_promotion_ledger_record_file_hash, _validate_promotion_ledger_record_matches_gate, _validate_promotion_ledger_source, _validate_promotion_policy_section, _validate_promotion_release_record, _validate_promotion_release_record_bindings, _validate_promotion_release_record_card_bindings, _validate_promotion_release_record_metrics, _validate_promotion_release_record_policy, _validate_promotion_release_record_validation, _validate_promotion_rollback_receipt, _validate_raw_promotion_policy, _validate_ref_matches_fingerprinted_artifact, _validate_registry_artifact_matches_alias_snapshot, _validate_repair_evidence_snippets, _validate_repair_item, _validate_repair_queue, _validate_repair_queue_metrics, _validate_repair_replay, _validate_repair_source_artifact_fingerprints, _validate_repair_source_artifacts, _validate_repair_source_file_ref, _validate_replay_bundle, _validate_replay_bundle_argv_inputs, _validate_replay_bundle_copied_lineage_inputs, _validate_replay_bundle_input_record, _validate_replay_bundle_lineage, _validate_strict_compact_validation_summary, validate_action_ledger, validate_action_ledger_gate, validate_action_ledger_payload_consistency, validate_decision_gate, validate_evidence_bundle, validate_improvement_ledger, validate_improvement_ledger_gate, validate_improvement_ledger_payload_consistency, validate_improvement_plan, validate_promotion_alias_apply, validate_promotion_archive, validate_promotion_cards, validate_promotion_decision, validate_promotion_ledger, validate_promotion_ledger_gate, validate_promotion_ledger_payload_consistency, validate_promotion_policy, validate_promotion_release_record, validate_promotion_rollback_receipt, validate_repair_queue, validate_replay_bundle
from ._validation.models import _validate_existing_path_field, _validate_model_adapter_manifest, _validate_model_candidate, _validate_model_compatibility_report, _validate_model_layer_file_ref, _validate_model_registry, _validate_model_registry_entry, _validate_model_registry_links_files, _validate_model_scout_manifest, _validate_model_serving_probe_receipt, _validate_training_plan, validate_model_adapter_manifest, validate_model_candidate, validate_model_compatibility_report, validate_model_registry, validate_model_registry_entry, validate_model_scout_manifest, validate_model_serving_probe_receipt, validate_training_plan
from ._validation.primitives import ValidationTarget, _ARCHIVE_RELATIONSHIP_KEYS, _archive_artifact_path, _archive_artifact_roles_by_name, _average_number, _count_family, _count_rows, _count_strings, _directory_contains_symlink, _directory_sha256, _directory_tree_fingerprint, _expected_suite_trend_delta, _expected_suite_trend_summary, _increment, _is_dataset_version, _is_int_between, _is_lowercase_sha256, _is_non_empty_string_list, _is_non_negative_int, _is_number_between, _is_optional_non_negative_int, _is_optional_non_negative_number, _is_optional_number, _is_optional_rate, _is_plain_int, _is_public_review_ref_path, _is_redacted_placeholder, _is_sha256, _is_string_list, _is_windows_absolute, _looks_absolute, _merge_count_rows, _non_negative_int_value, _number_delta, _number_value, _outcome_strings, _path_resolves_inside, _rate_value, _read_json_object_silent, _read_jsonl_objects, _read_jsonl_objects_optional, _read_object, _read_object_optional, _reject_archive_artifact_symlink_path, _reject_symlinked_validation_path, _require_equal, _reviewed_export_source_record, _score_value, _validate_allowed_keys, _validate_archive_relationship, _validate_count_map_object, _validate_count_rows, _validate_evidence_refs, _validate_gate_like_checks, _validate_metadata, _validate_metric_count_fields, _validate_metric_source, _validate_public_review_fingerprint_paths, _validate_public_review_ref_path, _warn_absolute_public_path
from ._validation.review import _REVIEWED_GATE_EFFECTIVE_POLICY_KEYS, _REVIEWED_GATE_KEYS, _REVIEW_CALIBRATION_CHECK_KEYS, _REVIEW_CALIBRATION_DISAGREEMENT_KEYS, _REVIEW_CALIBRATION_EFFECTIVE_POLICY_KEYS, _REVIEW_CALIBRATION_EXPECTED_MAX_KEYS, _REVIEW_CALIBRATION_EXPECTED_MIN_KEYS, _REVIEW_CALIBRATION_EXPECTED_VALIDATION_KEYS, _REVIEW_CALIBRATION_KEYS, _REVIEW_CALIBRATION_LABEL_COUNT_KEYS, _REVIEW_CALIBRATION_MAX_CHECK_IDS, _REVIEW_CALIBRATION_MEAN_SCORE_KEYS, _REVIEW_CALIBRATION_METRICS_KEYS, _REVIEW_CALIBRATION_MIN_CHECK_IDS, _REVIEW_CALIBRATION_SOURCE_KEYS, _REVIEW_CALIBRATION_SOURCE_PATH_ACTUAL_KEYS, _REVIEW_CALIBRATION_SOURCE_PATH_EXPECTED_KEYS, _REVIEW_CALIBRATION_VALIDATION_KEYS, _expected_reviewed_label_provenance, _is_public_review_calibration_ref_path, _label_count_rows, _review_item_passed, _reviewed_confidence_counts, _reviewed_gate_export_path, _reviewed_label_by_episode, _reviewed_label_counts, _reviewed_label_map, _reviewed_source_label, _validate_confidence_value, _validate_mean_score_by_human_label, _validate_pref_side_confidence, _validate_pref_side_hash, _validate_review_calibration, _validate_review_calibration_check_payload, _validate_review_calibration_disagreements, _validate_review_calibration_export_ref, _validate_review_calibration_label_ref, _validate_review_calibration_metrics, _validate_review_calibration_validation_metrics, _validate_review_confidence_link, _validate_review_item_hash_link, _validate_review_items, _validate_review_labels, _validate_review_manifest, _validate_reviewed_action_sft, _validate_reviewed_dataset_registry, _validate_reviewed_dpo, _validate_reviewed_labels, _validate_reviewed_manifest, _validate_reviewed_preferences, _validate_reviewed_reward_model, _validate_reviewed_sft, _validate_reviewed_trainer_view_replay, _validate_reviewed_trainer_views, validate_review_calibration, validate_review_export, validate_reviewed_export, validate_reviewed_gate
from ._validation.runs import _harness_canary_artifact_key, _harness_path_uses_symlink, _is_safe_runtime_router_ref_path, _lineage_basename, _lineage_records, _resolve_harness_artifact_path, _resolve_harness_canary_artifact_path, _resolve_harness_replay_artifact_path, _resolve_harness_suite_artifact_path, _resolve_router_artifact_ref, _router_promotion_decision_summary, _run_digest_api_call_count, _run_digest_evidence_counts, _run_digest_max_subagent_depth, _run_digest_rule_ref_count, _run_digest_trace_signal, _scorecard_evidence_ref_count, _validate_adapter_route_promotion_refs, _validate_harness_canary_artifact_record, _validate_harness_fake_secret_canaries, _validate_harness_fake_secret_canary_check, _validate_harness_matching_ref, _validate_harness_named_file_ref, _validate_harness_replay_artifact_ref, _validate_harness_replay_result, _validate_harness_run_artifact_ref, _validate_harness_run_manifest, _validate_harness_run_result, _validate_harness_suite_artifact_ref, _validate_harness_suite_result, _validate_harness_tool_policy, _validate_lineage, _validate_lineage_evidence_link, _validate_lineage_file_record, _validate_lineage_input_record, _validate_lineage_replay, _validate_live_smoke_environment, _validate_live_smoke_summary, _validate_run_digest, _validate_run_digest_evidence, _validate_run_digest_outcome, _validate_run_digest_rules, _validate_run_digest_state_changes, _validate_run_digest_trace_signal, _validate_run_digest_training, _validate_schema_contract_target, _validate_scorecard, _validate_snapshot_directory_entry, _validate_snapshot_directory_record, _validate_snapshot_file_record, _validate_snapshot_record_fingerprint, _validate_snapshot_verifiers, _validate_state_diff, _validate_state_diff_change, _validate_state_diff_summary, _validate_state_snapshot, _validate_task_completion, _validate_trace, _validate_trace_observability, _validate_trace_observability_metrics, _validate_trace_observability_runs, _validated_router_ref_payload, _warn_command_token_public_path, _warn_harness_sandbox_public_paths, _warn_harness_suite_run_public_paths, _warn_replay_metadata_public_paths, _warn_shell_tokens_public_paths, validate_adapter_route_decision_artifact, validate_harness_replay_result, validate_harness_run_manifest, validate_harness_run_result, validate_live_smoke_summary, validate_run_digest, validate_run_dir, validate_runs_dir, validate_state_diff, validate_state_snapshot, validate_tool_capability_selection_artifact, validate_trace_observability
from ._validation.trainer_archive import _TRAINER_ARCHIVE_APPROVED_COMMAND_KEYS, _TRAINER_ARCHIVE_ARTIFACT_KEYS, _TRAINER_ARCHIVE_CHECK_ARCHIVE_KEYS, _TRAINER_ARCHIVE_CHECK_CHECK_KEYS, _TRAINER_ARCHIVE_CHECK_CONSUMER_CONTRACT_KEYS, _TRAINER_ARCHIVE_CHECK_EXTERNAL_CODE_KEYS, _TRAINER_ARCHIVE_CHECK_EXTERNAL_PATH_KEYS, _TRAINER_ARCHIVE_CHECK_EXTERNAL_ROOT_KEYS, _TRAINER_ARCHIVE_CHECK_KEYS, _TRAINER_ARCHIVE_CHECK_METRICS_KEYS, _TRAINER_ARCHIVE_CHECK_PORTABLE_COMMAND_KEYS, _TRAINER_ARCHIVE_CHECK_TRAINER_INPUT_KEYS, _TRAINER_ARCHIVE_CHECK_VALIDATION_KEYS, _TRAINER_ARCHIVE_CONSUMER_CONTRACT_KEYS, _TRAINER_ARCHIVE_EXTERNAL_COMMAND_PATH_KEYS, _TRAINER_ARCHIVE_KEYS, _TRAINER_ARCHIVE_METRICS_KEYS, _TRAINER_ARCHIVE_MISSING_KEYS, _TRAINER_ARCHIVE_PATH_REWRITE_KEYS, _TRAINER_ARCHIVE_PORTABLE_COMMAND_KEYS, _TRAINER_ARCHIVE_TRAINER_INPUT_KEYS, _TRAINER_CONSUMER_PLAN_CHECK_KEYS, _TRAINER_CONSUMER_PLAN_EXECUTION_KEYS, _TRAINER_CONSUMER_PLAN_EXTERNAL_CODE_FILE_KEYS, _TRAINER_CONSUMER_PLAN_HANDOFF_KEYS, _TRAINER_CONSUMER_PLAN_KEYS, _TRAINER_CONSUMER_PLAN_METRICS_KEYS, _TRAINER_CONSUMER_PLAN_SOURCE_KEYS, _TRAINER_CONSUMER_PLAN_TRAINER_INPUT_KEYS, _TRAINER_CONSUMER_PLAN_VALIDATION_KEYS, _TRAINER_LAUNCH_CHECK_APPROVED_COMMAND_KEYS, _TRAINER_LAUNCH_CHECK_ARTIFACTS_KEYS, _TRAINER_LAUNCH_CHECK_CHECK_KEYS, _TRAINER_LAUNCH_CHECK_GATE_KEYS, _TRAINER_LAUNCH_CHECK_KEYS, _TRAINER_LAUNCH_CHECK_VALIDATION_KEYS, _TRAINER_PREFLIGHT_ARTIFACT_KEYS, _TRAINER_PREFLIGHT_CHECK_KEYS, _TRAINER_PREFLIGHT_DATASET_SELECTION_KEYS, _TRAINER_PREFLIGHT_GATE_KEYS, _TRAINER_PREFLIGHT_GATE_VALIDATION_KEYS, _TRAINER_PREFLIGHT_KEYS, _TRAINER_PREFLIGHT_ROW_SCHEMA_COUNT_KEYS, _TRAINER_PREFLIGHT_SCHEMA_CONTRACT_KEYS, _TRAINER_PREFLIGHT_TRAINER_COMMAND_KEYS, _TRAINER_PREFLIGHT_TRAINER_VIEWS_KEYS, _TRAINER_PREFLIGHT_TRAINER_VIEW_KEYS, _TRAINER_PREFLIGHT_VALIDATION_SUMMARY_KEYS, _TRAINER_PREFLIGHT_VALIDATION_TARGET_KEYS, _TRAINER_WRAPPER_DRY_RUN_CHECK_KEYS, _TRAINER_WRAPPER_DRY_RUN_CHECK_PAYLOAD_KEYS, _TRAINER_WRAPPER_DRY_RUN_CHECK_SCOPE_KEYS, _TRAINER_WRAPPER_DRY_RUN_EXTERNAL_CODE_FILE_KEYS, _TRAINER_WRAPPER_DRY_RUN_INPUTS_KEYS, _TRAINER_WRAPPER_DRY_RUN_KEYS, _TRAINER_WRAPPER_DRY_RUN_METRICS_KEYS, _TRAINER_WRAPPER_DRY_RUN_TRAINER_INPUT_KEYS, _TRAINER_WRAPPER_DRY_RUN_VALIDATION_KEYS, _TRAINER_WRAPPER_DRY_RUN_WOULD_RUN_KEYS, _expected_trainer_archive_rewrites, _is_safe_trainer_consumer_plan_command_path, _is_safe_trainer_wrapper_would_run_path, _replace_trainer_archive_path_value, _resolve_preflight_record_path, _resolve_trainer_launch_preflight_path, _rewrite_trainer_archive_command_argv, _rewrite_trainer_archive_command_token, _trainer_archive_alias_matches, _trainer_archive_count_map, _trainer_archive_external_command_paths, _trainer_archive_is_external_command_path, _trainer_archive_looks_like_path, _trainer_archive_tree_fingerprint, _trainer_consumer_plan_source_path, _trainer_input_from_artifact, _validate_approved_command, _validate_handoff_checks, _validate_launch_artifacts_summary, _validate_launch_check_command_token_public_path, _validate_launch_check_command_tokens_public_paths, _validate_launch_check_gate, _validate_launch_validation_record, _validate_preflight_directory_hash, _validate_preflight_file_hash, _validate_trainer_archive, _validate_trainer_archive_artifact, _validate_trainer_archive_check, _validate_trainer_archive_check_archive, _validate_trainer_archive_check_command_token_public_path, _validate_trainer_archive_check_command_tokens_public_paths, _validate_trainer_archive_check_consumer_contract, _validate_trainer_archive_check_external_code, _validate_trainer_archive_check_external_root, _validate_trainer_archive_check_inputs, _validate_trainer_archive_check_metrics, _validate_trainer_archive_check_portable_command, _validate_trainer_archive_check_validation, _validate_trainer_archive_commands, _validate_trainer_archive_consumer_contract, _validate_trainer_archive_inputs, _validate_trainer_archive_metrics, _validate_trainer_archive_missing, _validate_trainer_archive_rewrites, _validate_trainer_command, _validate_trainer_compact_validation_record, _validate_trainer_consumer_plan, _validate_trainer_consumer_plan_command_path, _validate_trainer_consumer_plan_command_token_public_path, _validate_trainer_consumer_plan_execution, _validate_trainer_consumer_plan_external_code_file, _validate_trainer_consumer_plan_handoff, _validate_trainer_consumer_plan_metrics, _validate_trainer_consumer_plan_source, _validate_trainer_consumer_plan_trainer_input, _validate_trainer_consumer_plan_validation, _validate_trainer_input_expected_payload, _validate_trainer_launch_check, _validate_trainer_launch_source_and_replay, _validate_trainer_preflight, _validate_trainer_preflight_artifact_record, _validate_trainer_preflight_control_artifact_declarations, _validate_trainer_preflight_dataset_selection, _validate_trainer_preflight_gate, _validate_trainer_preflight_reviewed_binding, _validate_trainer_preflight_schema_contract_record, _validate_trainer_preflight_trainer_views, _validate_trainer_preflight_validation_summaries, _validate_trainer_wrapper_check_payload, _validate_trainer_wrapper_checks, _validate_trainer_wrapper_dry_run, _validate_trainer_wrapper_external_code, _validate_trainer_wrapper_input, _validate_trainer_wrapper_inputs, _validate_trainer_wrapper_metrics, _validate_trainer_wrapper_validation, _validate_trainer_wrapper_would_run, _validate_trainer_wrapper_would_run_path, _validate_trainer_wrapper_would_run_token_public_path, _validate_visible_directory_hash, _validate_visible_file_hash, _visible_local_path, validate_trainer_archive, validate_trainer_archive_check, validate_trainer_consumer_plan, validate_trainer_launch_check, validate_trainer_preflight, validate_trainer_wrapper_dry_run
from ._validation.training_flow_result import _AGENTIC_TRAINING_FLOW_BOUNDARY_KEYS, _AGENTIC_TRAINING_FLOW_CHECK_KEYS, _AGENTIC_TRAINING_FLOW_COMMAND_KEYS, _AGENTIC_TRAINING_FLOW_DELEGATED_KEYS, _AGENTIC_TRAINING_FLOW_EXTERNAL_RUNNER_KEYS, _AGENTIC_TRAINING_FLOW_HANDOFF_KEYS, _AGENTIC_TRAINING_FLOW_KEYS, _AGENTIC_TRAINING_FLOW_METRIC_KEYS, _AGENTIC_TRAINING_FLOW_MODE_CONTRACT_KEYS, _AGENTIC_TRAINING_FLOW_MODE_GATE_KEYS, _AGENTIC_TRAINING_FLOW_REWARD_CONTRACT_KEYS, _AGENTIC_TRAINING_FLOW_SIDE_EFFECT_KEYS, _AGENTIC_TRAINING_FLOW_SOURCE_ARTIFACT_KEYS, _AGENTIC_TRAINING_FLOW_SOURCE_REF_KEYS, _AGENTIC_TRAINING_FLOW_STAGE_KEYS, _AGENTIC_TRAINING_RESULT_ARTIFACT_KEYS, _AGENTIC_TRAINING_RESULT_BOUNDARY_KEYS, _AGENTIC_TRAINING_RESULT_CHECK_KEYS, _AGENTIC_TRAINING_RESULT_FAILURE_KEYS, _AGENTIC_TRAINING_RESULT_HANDOFF_KEYS, _AGENTIC_TRAINING_RESULT_KEYS, _AGENTIC_TRAINING_RESULT_LINEAGE_KEYS, _AGENTIC_TRAINING_RESULT_LINEAGE_REF_KEYS, _AGENTIC_TRAINING_RESULT_MANIFEST_REF_KEYS, _AGENTIC_TRAINING_RESULT_METRIC_KEYS, _AGENTIC_TRAINING_RESULT_REGISTRY_LINK_KEYS, _AGENTIC_TRAINING_RESULT_REGISTRY_UPDATE_KEYS, _AGENTIC_TRAINING_RESULT_TRAINING_KEYS, _agentic_training_result_output_artifact_counter, _agentic_training_result_plan_input_manifests, _agentic_training_result_redacted_path, _agentic_training_result_reference_path, _is_safe_agentic_training_result_path, _is_safe_or_redacted_training_flow_path, _is_safe_training_flow_metadata_path, _model_scout_reference_path, _repo_root_for_artifact, _validate_agentic_training_flow, _validate_agentic_training_flow_boundary, _validate_agentic_training_flow_command, _validate_agentic_training_flow_command_path, _validate_agentic_training_flow_command_token_public_path, _validate_agentic_training_flow_contract, _validate_agentic_training_flow_delegated_flow, _validate_agentic_training_flow_external_runner_contract, _validate_agentic_training_flow_metrics, _validate_agentic_training_flow_mode_contract_check, _validate_agentic_training_flow_mode_gate, _validate_agentic_training_flow_reward_contract, _validate_agentic_training_flow_side_effect_boundary, _validate_agentic_training_flow_source_ref, _validate_agentic_training_flow_sources, _validate_agentic_training_result, _validate_agentic_training_result_artifacts, _validate_agentic_training_result_boundary, _validate_agentic_training_result_contract, _validate_agentic_training_result_flow_lineage, _validate_agentic_training_result_lineage, _validate_agentic_training_result_lineage_file, _validate_agentic_training_result_manifest_matches_plan, _validate_agentic_training_result_registry_update, validate_agentic_training_flow, validate_agentic_training_result
from ._validation.training_loop import AGENTIC_LOOP_CLOUD_TRAINING_HANDOFF_ROLES, AGENTIC_LOOP_CLOUD_TRAINING_ROLES, _AGENTIC_LOOP_LEDGER_BASIC_GROUP_KEYS, _AGENTIC_LOOP_LEDGER_BOUNDARY_KEYS, _AGENTIC_LOOP_LEDGER_CLOUD_TRAINING_KEYS, _AGENTIC_LOOP_LEDGER_COST_KEYS, _AGENTIC_LOOP_LEDGER_DECISION_KEYS, _AGENTIC_LOOP_LEDGER_DIGEST_KEYS, _AGENTIC_LOOP_LEDGER_GOVERNANCE_ACTION_KEYS, _AGENTIC_LOOP_LEDGER_GOVERNANCE_KEYS, _AGENTIC_LOOP_LEDGER_ITERATION_KEYS, _AGENTIC_LOOP_LEDGER_KEYS, _AGENTIC_LOOP_LEDGER_METRICS_KEYS, _AGENTIC_LOOP_LEDGER_NEXT_ACTION_KEYS, _AGENTIC_TRAINING_LOOP_ARTIFACT_REF_KEYS, _AGENTIC_TRAINING_LOOP_BUDGET_KEYS, _AGENTIC_TRAINING_LOOP_CHECK_KEYS, _AGENTIC_TRAINING_LOOP_CLOUD_COMPLETION_STATE_KEYS, _AGENTIC_TRAINING_LOOP_CLOUD_LINEAGE_KEYS, _AGENTIC_TRAINING_LOOP_CLOUD_LINEAGE_LINK_KEYS, _AGENTIC_TRAINING_LOOP_CLOUD_LINEAGE_PROVIDER_KEYS, _AGENTIC_TRAINING_LOOP_CLOUD_RECEIPT_STATE_KEYS, _AGENTIC_TRAINING_LOOP_CLOUD_TRAINING_KEYS, _AGENTIC_TRAINING_LOOP_EXECUTION_BOUNDARY_KEYS, _AGENTIC_TRAINING_LOOP_EXTERNAL_EVAL_RECEIPT_STATE_KEYS, _AGENTIC_TRAINING_LOOP_HANDOFF_CONTRACT_KEYS, _AGENTIC_TRAINING_LOOP_NEXT_ITERATION_KEYS, _AGENTIC_TRAINING_LOOP_PARTICIPANTS_KEYS, _AGENTIC_TRAINING_LOOP_PHASE_KEYS, _AGENTIC_TRAINING_LOOP_PLAN_KEYS, _AGENTIC_TRAINING_LOOP_PROVIDER_CONSTRAINTS_KEYS, _AGENTIC_TRAINING_LOOP_ROLE_COUNT_KEYS, _agentic_loop_count_map, _agentic_loop_role_count, _agentic_loop_role_ready, _agentic_training_loop_cloud_training_boundary, _agentic_training_loop_cloud_training_launch, _agentic_training_loop_cloud_training_status, _agentic_training_loop_external_eval_adapter_contract, _agentic_training_loop_external_eval_adapter_receipts, _agentic_training_loop_external_eval_boundary, _agentic_training_loop_external_eval_launch, _agentic_training_loop_first_payload, _agentic_training_loop_first_ref, _agentic_training_loop_payload_has_public_unsafe_path, _agentic_training_loop_payload_records, _agentic_training_loop_payloads, _agentic_training_loop_provider_id, _agentic_training_loop_public_path_field, _agentic_training_loop_registry_provider_ids, _agentic_training_loop_resolved_artifact_paths, _agentic_training_loop_role_source_ready, _agentic_training_loop_source_validation_state, _expected_agentic_training_loop_cloud_training_lineage, _expected_agentic_training_loop_cloud_training_link, _expected_agentic_training_loop_cloud_training_provider_lineage, _expected_agentic_training_loop_cloud_training_receipt_state, _expected_agentic_training_loop_cloud_training_role_counts, _expected_agentic_training_loop_external_eval_receipt_state, _is_safe_agentic_loop_governance_path, _is_safe_next_iteration_schedule_path, _next_iteration_compact_decision, _next_iteration_compact_metrics, _next_iteration_schedule_ref_path, _resolve_agentic_loop_ledger_source_path, _resolve_agentic_training_loop_plan_ref_path, _safe_non_negative_int, _safe_non_negative_number, _validate_agentic_loop_governance_checks, _validate_agentic_loop_governance_decision, _validate_agentic_loop_governance_receipt, _validate_agentic_loop_governance_requested_action, _validate_agentic_loop_governance_requested_action_matches, _validate_agentic_loop_governance_source_action, _validate_agentic_loop_governance_source_ledger, _validate_agentic_loop_governance_source_snapshots, _validate_agentic_loop_governance_unreplayable_source_state, _validate_agentic_loop_ledger, _validate_agentic_loop_ledger_basic_group, _validate_agentic_loop_ledger_cloud_training, _validate_agentic_loop_ledger_cloud_training_completion_state, _validate_agentic_loop_ledger_cloud_training_lineage, _validate_agentic_loop_ledger_cloud_training_receipt_state, _validate_agentic_loop_ledger_cost_estimate, _validate_agentic_loop_ledger_counts, _validate_agentic_loop_ledger_decision, _validate_agentic_loop_ledger_digest, _validate_agentic_loop_ledger_external_eval_receipt_state, _validate_agentic_loop_ledger_next_actions, _validate_agentic_loop_ledger_source, _validate_agentic_training_loop_cloud_training, _validate_agentic_training_loop_cloud_training_completion_state, _validate_agentic_training_loop_cloud_training_lineage, _validate_agentic_training_loop_cloud_training_receipt_state, _validate_agentic_training_loop_external_eval_receipt_state, _validate_agentic_training_loop_object_keys, _validate_agentic_training_loop_plan, _validate_agentic_training_loop_plan_phase, _validate_agentic_training_loop_plan_ref, _validate_agentic_training_loop_role_count_rows, _validate_next_iteration_pressure_matches_sources, _validate_next_iteration_schedule, _validate_next_iteration_schedule_ref, _validate_next_iteration_schedule_ref_metrics, validate_agentic_loop_governance_receipt, validate_agentic_loop_ledger, validate_agentic_training_loop_plan, validate_next_iteration_schedule
from ._validation.training_plan_runtime import _AGENTIC_TRAINING_PLAN_ADVANCED_REQUIRED_FLAG, _AGENTIC_TRAINING_PLAN_BLOCK_RECOMMENDATION, _AGENTIC_TRAINING_PLAN_CHECK_KEYS, _AGENTIC_TRAINING_PLAN_DATASET_MANIFEST_KEYS, _AGENTIC_TRAINING_PLAN_DATA_REQUIREMENT_EVIDENCE_KEYS, _AGENTIC_TRAINING_PLAN_DATA_REQUIREMENT_KEYS, _AGENTIC_TRAINING_PLAN_DEFAULT_REQUIRED_FLAG, _AGENTIC_TRAINING_PLAN_EXECUTION_KEYS, _AGENTIC_TRAINING_PLAN_EXTENSION_POINT_KEYS, _AGENTIC_TRAINING_PLAN_EXTERNAL_RUNNER_KEYS, _AGENTIC_TRAINING_PLAN_FUTURE_RL_REQUIRED_FLAG, _AGENTIC_TRAINING_PLAN_HANDOFF_KEYS, _AGENTIC_TRAINING_PLAN_INPUT_MANIFEST_KEYS, _AGENTIC_TRAINING_PLAN_KEYS, _AGENTIC_TRAINING_PLAN_MODEL_MANIFEST_KEYS, _AGENTIC_TRAINING_PLAN_MODE_CONTRACT_KEYS, _AGENTIC_TRAINING_PLAN_PLANNING_GATE_KEYS, _AGENTIC_TRAINING_PLAN_READY_RECOMMENDATION, _AGENTIC_TRAINING_PLAN_REWARD_CONTRACT_KEYS, _AGENTIC_TRAINING_PLAN_REWARD_KIND, _AGENTIC_TRAINING_PLAN_REWARD_SIGNATURE, _AGENTIC_TRAINING_PLAN_REWARD_VALIDATE_MODES, _AGENTIC_TRAINING_PLAN_SIDE_EFFECT_KEYS, _AGENTIC_TRAINING_PLAN_TRAINER_PLAN_KEYS, _AGENTIC_TRAINING_PLAN_VIEW_KEYS, _agentic_training_plan_mode_category, _agentic_training_plan_required_flag, _is_nested_string_list, _resolve_runtime_preflight_plan_path, _validate_agentic_training_plan, _validate_agentic_training_plan_command_token_public_path, _validate_agentic_training_plan_data_requirement_evidence, _validate_agentic_training_plan_data_requirements, _validate_agentic_training_plan_execution, _validate_agentic_training_plan_external_runner_contract, _validate_agentic_training_plan_handoff_contract, _validate_agentic_training_plan_input_manifests, _validate_agentic_training_plan_manifest_ref, _validate_agentic_training_plan_mode_contract, _validate_agentic_training_plan_planning_gate, _validate_agentic_training_plan_reward_contract, _validate_agentic_training_plan_side_effect_boundary, _validate_agentic_training_plan_trainer_plan, _validate_agentic_training_plan_view, _validate_agentic_training_plan_views, _validate_agentic_training_runtime_preflight, _validate_runtime_preflight_handoff, _validate_runtime_preflight_side_effect_boundary, validate_agentic_training_plan, validate_agentic_training_runtime_preflight
